trailingComma: "all"
singleQuote: true
tabWidth: 4
overrides:
  - files: ["*.json"]
    options:
      tabWidth: 2
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false
      tabWidth: 2
  - files: ["*.md"]
    options:
      tabWidth: 2
      proseWrap: always
