name: ci
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python project
        uses: ./.github/actions/setup-python
        with:
          tool-versions-path: .tool-versions

      - run: mkdocs build
